apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
  namespace: ata
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - name: mariadb
        image: mariadb:11.8.1-rc
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: 1 2 ali @ # رمز عبور ساده (توصیه نمی‌شود برای محیط تولید)
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mariadb-data
          mountPath: /var/lib/mysql
      volumes:
      - name: mariadb-data
        hostPath:
          path: /ata/mariadb
          type: DirectoryOrCreate

---
apiVersion: v1
kind: Service
metadata:
  name: mariadb
  namespace: ata
spec:
  selector:
    app: mariadb
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
