version: '3'
services:
  wiki:
    image: requarks/wiki:latest
    container_name: wiki
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      DB_TYPE: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: wikijs
      DB_PASS: 12@123
      DB_NAME: wiki
    volumes:
      - wiki-data:/var/wiki
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    container_name: wiki-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: wikijs
      POSTGRES_PASSWORD: 12@123
      POSTGRES_DB: wiki
    volumes:
      - wiki-db:/var/lib/postgresql/data

volumes:
  wiki-data:
  wiki-db:
