version: '3.8'

services:
  flowable-ui:
    image: flowable/flowable-ui:6.8.0
    container_name: flowable-ui
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.h2.Driver
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:flowable;DB_CLOSE_DELAY=-1
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=test
    volumes:
      - flowable-ui-app:/opt/flowable-ui/app
    restart: unless-stopped

volumes:
  flowable-ui-app:
